### ISSUE TITLE
Error in Prime number Program 

### ISSUE THREAD

**Issue by shiwanibiradar** [Easyvipin/Practice-Python#27]
One of the Program in Prime Number shows wrong output . 4 is not a prime number but it shows it is prime number so i want to work on this issue #Hacktoberfest

**Comment by ghost** [comment]
Hello , I've tweaked the program, it should work now

**Comment by ghost** [comment]
I've made a PR with the changes . Should work now

**Comment by Easyvipin** [comment]
assign the issue. @shiwanibiradar

**Comment by Easyvipin** [comment]
@

> I've made a PR with the changes . Should work now

not its not working properly :)

**Comment by shiwanibiradar** [comment]
I think i already worked on this. and now its working properly  so closing this issue

**Comment by ghost** [comment]
> I think i already worked on this. and now its working properly so closing this issue

aight ok , what did you change in the program ?
